# ---

# root: true

# env:
#   browser: true
#   es2021: true
#   node: true
# extends:
#   - airbnb
#   - eslint:recommended
#   - plugin:react/recommended
# overrides: []
# settings:
#   import/resolver:
#     - node
#     - webpack
# parserOptions:
#   ecmaVersion: latest
#   sourceType: module
# plugins:
#   - react
# rules: {}

---

env:
  browser: true
  es2021: true
  node: true

extends:
  - 'airbnb-base'
  
# Включает поддержку конструкции import.meta.url
parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] 
